service: nest-back-store

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 512
  timeout: 10
  stage: dev
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_NAME: ${env:DB_NAME}
    NODE_ENV: ${env:NODE_ENV}
    DB_SSL: ${env:DB_SSL}
    CORS_ORIGIN: ${env:CORS_ORIGIN}
    PUB_KEY: ${env:PUB_KEY}
    PRV_KEY: ${env:PRV_KEY}
    INTEGRITY_KEY: ${env:INTEGRITY_KEY}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
      Resource: "*"

custom:
  dotenv:
    path: .env.dev

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
    vpc:
      securityGroupIds:
        - sg-0138114ce5d82548a
      subnetIds:
        - subnet-00096191a1339e66f
        - subnet-0641d2db0df108262
